micronaut:
  application:
    name: tasklist
  config:
    files: application.yml
  server:
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
h2:
  url: jdbc:h2:./tasks